In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('/home/kumar/Machine_Learning/datasets1.csv')

In [3]:
df.head()

Price  Year  Mileage              City State                Vin   Make  \
0   8995  2014    35725           El Paso    TX  19VDE2E53EE000083  Acura   
1  10888  2013    19606  Long Island City    NY  19VDE1F52DE012636  Acura   
2   8995  2013    48851           El Paso    TX  19VDE2E52DE000025  Acura   
3  10999  2014    39922           Windsor    CO  19VDE1F71EE003817  Acura   
4  14799  2016    22142            Lindon    UT  19UDE2F32GA001284  Acura   

          Model  
0    ILX6-Speed  
1    ILX5-Speed  
2    ILX6-Speed  
3    ILX5-Speed  
4  ILXAutomatic

In [7]:
X = df.iloc[:,-2]


In [9]:
X.nunique()

58

In [35]:
df.head()


R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [36]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [16]:
one_hot = pd.get_dummies(df['Make'])

In [17]:
one_hot

AM  Acura  Alfa  Aston  Audi  BMW  Bentley  Buick  Cadillac  \
0        0      1     0      0     0    0        0      0         0   
1        0      1     0      0     0    0        0      0         0   
2        0      1     0      0     0    0        0      0         0   
3        0      1     0      0     0    0        0      0         0   
4        0      1     0      0     0    0        0      0         0   
5        0      1     0      0     0    0        0      0         0   
6        0      1     0      0     0    0        0      0         0   
7        0      1     0      0     0    0        0      0         0   
8        0      1     0      0     0    0        0      0         0   
9        0      1     0      0     0    0        0      0         0   
10       0      1     0      0     0    0        0      0         0   
11       0      1     0      0     0    0        0      0         0   
12       0      1     0      0     0    0        0      0         0   
13       0      1     0      0     0    0        0      0         0   
14       0      1     0      0     0    0        0      0         0   
15       0      1     0      0     0    0        0      0         0   
16       0      1     0      0     0    0        0      0         0   
17       0      1     0      0     0    0        0      0         0   
18       0      1     0      0     0    0        0      0         0   
19       0      1     0      0     0    0        0      0         0   
20       0      1     0      0     0    0        0      0         0   
21       0      1     0      0     0    0        0      0         0   
22       0      1     0      0     0    0        0      0         0   
23       0      1     0      0     0    0        0      0         0   
24       0      1     0      0     0    0        0      0         0   
25       0      1     0      0     0    0        0      0         0   
26       0      1     0      0     0    0        0      0         0   
27       0      1     0      0     0    0        0      0         0   
28       0      1     0      0     0    0        0      0         0   
29       0      1     0      0     0    0        0      0         0   
...     ..    ...   ...    ...   ...  ...      ...    ...       ...   
852092   0      0     0      0     0    0        0      0         0   
852093   0      0     0      0     0    0        0      0         0   
852094   0      0     0      0     0    0        0      0         0   
852095   0      0     0      0     0    0        0      0         0   
852096   0      0     0      0     0    0        0      0         0   
852097   0      0     0      0     0    0        0      0         0   
852098   0      0     0      0     0    0        0      0         0   
852099   0      0     0      0     0    0        0      0         0   
852100   0      0     0      0     0    0        0      0         0   
852101   0      0     0      0     0    0        0      0         0   
852102   0      0     0      0     0    0        0      0         0   
852103   0      0     0      0     0    0        0      0         0   
852104   0      0     0      0     0    0        0      0         0   
852105   0      0     0      0     0    0        0      0         0   
852106   0      0     0      0     0    0        0      0         0   
852107   0      0     0      0     0    0        0      0         0   
852108   0      0     0      0     0    0        0      0         0   
852109   0      0     0      0     0    0        0      0         0   
852110   0      0     0      0     0    0        0      0         0   
852111   0      0     0      0     0    0        0      0         0   
852112   0      0     0      0     0    0        0      0         0   
852113   0      0     0      0     0    0        0      0         0   
852114   0      0     0      0     0    0        0      0         0   
852115   0      0     0      0     0    0        0      0         0   
852116   0      0     0      0  

In [15]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
#X = labelencoder.fit_transform(X)
onehotencoder = OneHotEncoder(categorical_features = ['Make'])
df['Make'] = onehotencoder.fit_transform(df['Make']).toarray()

/home/kumar/.local/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


IndexError: tuple index out of range

In [12]:
X

array([ 1,  1,  1, ..., 56, 56, 56])

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('/home/kumar/Machine_Learning/Multiple_Linear_Regression/50_Startups.csv')
X = dataset.iloc[:, 1].values
y = dataset.iloc[:, 4].values
X = X.reshape(50,1)
y = y.reshape(50,1)


# Encoding categorical data
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# labelencoder = LabelEncoder()
# X[:, 3] = labelencoder.fit_transform(X[:, 3])
# onehotencoder = OneHotEncoder(categorical_features = [3])
# X = onehotencoder.fit_transform(X).toarray()

In [12]:
dataset.head()


R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

[103015.20159796 132582.27760816 132447.73845175  71976.09851258
 178537.48221056 116161.24230165  67851.69209676  98791.73374687
 113969.43533013 167921.06569551] [103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]


In [13]:
# X = X[:,1:]

In [14]:
y.reshape(50,1)

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [15]:
type(X)

numpy.ndarray

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
regressor = LinearRegression()

In [19]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [20]:
y_pred = regressor.predict(X_test)

In [23]:
X_test.shape

(10, 1)

[103015.20159796 132582.27760816 132447.73845175  71976.09851258
 178537.48221056 116161.24230165  67851.69209676  98791.73374687
 113969.43533013 167921.06569551] [103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]

In [22]:
print(y_pred,y_test)

[[140250.64343397]
 [ 93018.2761663 ]
 [102793.56983954]
 [ 89337.71057162]
 [ 97881.58809204]
 [111771.87828564]
 [ 79583.55463555]
 [124683.97368388]
 [109130.02504615]
 [ 92810.93295208]] [[103282.38]
 [144259.4 ]
 [146121.95]
 [ 77798.83]
 [191050.39]
 [105008.31]
 [ 81229.06]
 [ 97483.56]
 [110352.25]
 [166187.94]]


In [11]:
import statsmodels.formula.api as sm

In [12]:
dataset.shape

(50, 5)

In [13]:
X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)

In [14]:
X

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [25]:
X_opt = X[:,[0,3]]

In [26]:
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()

In [27]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Mon, 22 Apr 2019   Prob (F-statistic):           3.50e-32
Time:                        17:32:29   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""